# Generated by Django 2.2.12 on 2020-05-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(default='Inactive', max_length=15, verbose_name='Plan Status'),
        ),
    ]
