# Generated by Django 2.2.12 on 2020-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('On Hold', 'On Hold')], default='Inactive', max_length=15, verbose_name='Plan Status'),
        ),
    ]
