# Generated by Django 2.2.12 on 2020-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200504_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('On Hold', 'On Hold')], default='Inactive', max_length=15, verbose_name='Subscription Status'),
        ),
    ]
