# Generated by Django 2.2.12 on 2020-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200504_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='approved',
        ),
        migrations.AddField(
            model_name='subscription',
            name='feedback',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Feedback'),
        ),
    ]
