# Generated by Django 2.2.4 on 2020-05-12 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0008_auto_20200509_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='paid_untill',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMenthod', models.CharField(max_length=150)),
                ('customer_Id', models.CharField(max_length=150)),
                ('subscription_ID', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
