# Generated by Django 2.2.4 on 2020-05-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20200512_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2020-5-20'),
            preserve_default=False,
        ),
    ]
