# Generated by Django 2.2.4 on 2020-05-12 04:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0010_keys_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keys',
            new_name='Api_key',
        ),
    ]
