# Generated by Django 2.2.12 on 2020-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20200512_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='total_slots',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='Total Fixed Slots'),
        ),
    ]
