# Generated by Django 2.2.12 on 2020-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20200515_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='leaveRequest',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Leave Request'),
        ),
    ]
