# Generated by Django 2.2.12 on 2020-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_plan_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='leaveRequest',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Leave Request'),
        ),
    ]
