# Generated by Django 2.2.12 on 2020-05-16 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0018_categoryplanname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('last4', models.CharField(max_length=150)),
                ('exp_month', models.CharField(max_length=150)),
                ('exp_year', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=150)),
                ('default', models.BooleanField(blank=True, default='False')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
